### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by epicfaace** [rahular/itihasa#2]
Hey @rahular , thanks for this great repository! Some questions:

- English versions: Your paper mentions that both of the Sanskrit translations are by Dutt. Do you have more details on where the Sanskrit versions came from (which version / manuscript of the Mahabharata / Ramayana it came from)?
- License / copyright: I believe the translations by Dutt (and I think the original Sanskrit too) should be in the public domain -- but would you be able to put a license on this repository itself to specify that fact and also license the code in this repository itself?

Thanks!

**Comment by rahular** [comment]
Hi @epicfaace, thanks for your interest.
- These translations were published in the late 1800s and early 1900s. So they are definitely not the critical editions. However, while cleaning the data I remember reading inline notes like "these shlokas are only present in edition X, and not in others". But I have not kept those notes in the final processed data and we will have to go through the pdfs to find them.
- Would be happy to add a license. BTW what are you planning to do with the data?

**Comment by epicfaace** [comment]
Thanks! If you find out more details as to what the Sanskrit versions are, do let me know! I remember reading somewhere that Dutt's translation of the Mahabharata comes from Nilakantha's commentary on the Northern recension, but I'm not quite sure if that's correct or if that implies that the slokas correspond with this version.

I'm interested in:
- displaying the side-by-side Sanskrit text, verse-by-verse translation, and potentially doing a word-for-word translation myself in a nice website inspired by https://suttacentral.net/dhp/en/buddharakkhita. There's really no canonical, nicely indexed Mahabharata or Ramayana available online, unlike this site for the Bhagavad Gita (https://www.holy-bhagavad-gita.org/chapter/1/verse/1).
- experimenting further with improving your results with machine translation, such as tokenization of input by splitting sandhis.

Let me know if you're already working on some of these things and potentially collaborating!

**Comment by rahular** [comment]
There are actually a couple of nice (ongoing?) efforts.
- https://www.valmiki.iitk.ac.in/
- https://www.wisdomlib.org/hinduism/book/mahabharata-sanskrit
- You might have already seen my auto-generated site: http://www.rahular.com/itihasa/

I have stopped working on this now mainly due to lack of time but would be happy to collaborate (especially in extending this data. I have only scratched the surface.)
