### ISSUE TITLE
Request for Access to Embedding Files

### ISSUE THREAD

**Issue by shantanuo** [rahular/itihasa#6]
Are the generated embedding files available on GitHub? 

If not, I would need to regenerate the embeddings using my own API key, which could result in significant costs and time. If the embeddings have already been generated, please publish them to avoid unnecessary duplication of effort and expenses.

**Comment by rahular** [comment]
They should be in the faiss index: `https://github.com/rahular/itihasa/blob/gh-pages/res/index.bin` and you can retrieve them using the method shown [here](https://stackoverflow.com/a/76845658).

**Comment by shantanuo** [comment]
Thanks for the info.
git clone command did not download that file. So I missed it.
Looks like lfs is required to be installed:

```
apt-get install git-lfs
git lfs install
```
